# Generated by Django 5.1.2 on 2024-11-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_alter_anime_personaje_imagenanime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes'),
        ),
        migrations.DeleteModel(
            name='ImagenAnime',
        ),
    ]
